# Generated by Django 5.2.1 on 2025-09-14 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialLeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cred_type', models.CharField(choices=[('email', 'Email'), ('username', 'Username'), ('domain', 'Domain')], max_length=20)),
                ('value', models.CharField(max_length=320)),
                ('source', models.CharField(max_length=64)),
                ('source_url', models.URLField(blank=True)),
                ('leak_date', models.DateTimeField(blank=True, null=True)),
                ('severity', models.IntegerField(default=50)),
                ('plaintext', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cred_type', models.CharField(choices=[('email', 'Email'), ('username', 'Username'), ('domain', 'Domain')], max_length=20)),
                ('value', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
