# Generated by Django 5.2.1 on 2025-09-23 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socradar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredcredential',
            name='cred_type',
        ),
        migrations.RemoveField(
            model_name='monitoredcredential',
            name='user',
        ),
        migrations.RemoveField(
            model_name='monitoredcredential',
            name='value',
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitored_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
