# Generated by Django 5.2.1 on 2025-10-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socradar', '0003_telegramchannel_telegrammessage_dataleak'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('username', models.CharField(max_length=255)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='github', max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('crawl_session_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credential_leaks_found', models.BooleanField(default=False)),
                ('leak_count', models.IntegerField(default=0)),
                ('investigation_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-crawled_at'],
                'unique_together': {('username', 'crawl_session_id')},
            },
        ),
    ]
