# Generated by Django 5.2.1 on 2025-10-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socradar', '0004_crawledurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredcredential',
            name='credential_type',
            field=models.CharField(choices=[('email', 'Email'), ('username', 'Username'), ('domain', 'Domain'), ('custom', 'Custom Pattern')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='custom_value',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='credentialleak',
            name='cred_type',
            field=models.CharField(choices=[('email', 'Email'), ('username', 'Username'), ('domain', 'Domain'), ('custom', 'Custom Pattern')], max_length=20),
        ),
    ]
