# Generated by Django 5.2.1 on 2025-10-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socradar', '0005_monitoredcredential_credential_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredcredential',
            name='credit_card',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='monitoredcredential',
            name='ssn',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
