# Generated by Django 5.2.1 on 2025-10-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socradar', '0006_monitoredcredential_credit_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredcredential',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='monitoredcredential',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='monitoredcredential',
            name='ssn',
        ),
    ]
