# Generated by Django 4.2.25 on 2025-10-22 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socradar', '0007_remove_monitoredcredential_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegrammessage',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='has_links',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='link_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('error', 'Error'), ('timeout', 'Timeout'), ('redirect', 'Redirect')], default='pending', max_length=20)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('final_url', models.URLField(blank=True, max_length=2000)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('content_length', models.BigIntegerField(blank=True, null=True)),
                ('is_telegram_link', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='socradar.telegramchannel')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='socradar.telegrammessage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['validation_status'], name='socradar_te_validat_2c61cc_idx'), models.Index(fields=['created_at'], name='socradar_te_created_518ffd_idx'), models.Index(fields=['is_suspicious'], name='socradar_te_is_susp_8d5568_idx')],
                'unique_together': {('message', 'url')},
            },
        ),
    ]
