# Generated by Django 4.2.25 on 2025-10-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socradar', '0008_alter_telegrammessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='validation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='validation_status',
            field=models.CharField(choices=[('PUBLIC_OK', 'Public & Active'), ('NOT_FOUND', 'Not Found'), ('AUTH_ERROR', 'Authentication Error'), ('AUTH_TIMEOUT', 'Authentication Timeout'), ('FLOODWAIT', 'Rate Limited'), ('RPC_ERROR', 'API Error'), ('NO_API_CREDENTIALS', 'No API Credentials'), ('TELEGRAM_LIBRARY_MISSING', 'Library Missing'), ('ERROR', 'Connection Error'), ('PENDING', 'Pending Validation')], default='PENDING', max_length=50),
        ),
    ]
