# Generated by Django 4.2.25 on 2025-10-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socradar', '0009_telegramchannel_validation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='last_scraped_msg_id',
            field=models.BigIntegerField(default=0, help_text='Last scraped message ID for incremental scraping'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='scraping_error',
            field=models.TextField(blank=True, help_text='Last scraping error message', null=True),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='scraping_status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=20),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='scraping_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for current scraping job', max_length=255, null=True),
        ),
    ]
