# Generated by Django 4.2.25 on 2025-10-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socradar', '0010_telegramchannel_last_scraped_msg_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_uri', models.CharField(help_text='S3 URI of the file in MinIO', max_length=1000)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('file_extension', models.CharField(max_length=10)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('emails_count', models.IntegerField(default=0)),
                ('passwords_count', models.IntegerField(default=0)),
                ('usernames_count', models.IntegerField(default=0)),
                ('domains_count', models.IntegerField(default=0)),
                ('ip_addresses_count', models.IntegerField(default=0)),
                ('phones_count', models.IntegerField(default=0)),
                ('credit_cards_count', models.IntegerField(default=0)),
                ('ssns_count', models.IntegerField(default=0)),
                ('credentials_count', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score 0-100')),
                ('is_sensitive', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_files', to='socradar.telegrammessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('credit_card', models.CharField(blank=True, max_length=20)),
                ('ssn', models.CharField(blank=True, max_length=15)),
                ('extraction_method', models.CharField(default='regex', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score 0.0-1.0')),
                ('is_verified', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_credentials', to='socradar.telegrammessage')),
                ('processed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='socradar.processedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='processedfile',
            index=models.Index(fields=['processing_status'], name='socradar_pr_process_6e25f3_idx'),
        ),
        migrations.AddIndex(
            model_name='processedfile',
            index=models.Index(fields=['risk_score'], name='socradar_pr_risk_sc_3bb418_idx'),
        ),
        migrations.AddIndex(
            model_name='processedfile',
            index=models.Index(fields=['is_sensitive'], name='socradar_pr_is_sens_88e8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='processedfile',
            index=models.Index(fields=['processed_at'], name='socradar_pr_process_31bae8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processedfile',
            unique_together={('message', 's3_uri')},
        ),
        migrations.AddIndex(
            model_name='extractedcredential',
            index=models.Index(fields=['email'], name='socradar_ex_email_4dd218_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedcredential',
            index=models.Index(fields=['domain'], name='socradar_ex_domain_8ffc95_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedcredential',
            index=models.Index(fields=['risk_level'], name='socradar_ex_risk_le_9dc3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedcredential',
            index=models.Index(fields=['is_verified'], name='socradar_ex_is_veri_174c20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='extractedcredential',
            unique_together={('processed_file', 'email', 'password')},
        ),
    ]
