# Generated by Django 5.2.1 on 2025-10-02 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
